Finally. A sorting
cypok/tomp-git-exercises pull request #34
Opened 2022-10-17 15:32 UTC by Isn0v

And another one homework

2022-10-21 11:26 UTC, cypok requested changes

2022-10-21 11:26 UTC, cypok commented on sort.py
> +        print("comparing {} and {}".format(arr[j], arr[i]))
Тут есть проблемка: `arr[i]` меняется во время сортировки. Надо использовать `a_i`.

2022-10-23 08:37 UTC, Isn0v commented
Сделал по идее

2022-10-24 03:17 UTC, cypok commented
Отлично!

2022-10-24 03:17 UTC, closed without merging