Sorting
cypok/tomp-git-exercises pull request #62
Opened 2023-10-14 13:39 UTC by Alexey-shishkin4

Merge faster-sorting branch into sorting branch

2023-10-16 20:07 UTC, cypok requested changes
Так не пойдет, нужно переделать. Если есть вопросы -- спрашивайте.
Чтобы вернуть в начало:
```
$ git branch -D sorting
$ git switch --create sorting 32f8878
$ # merge and resolve conflicts here
$ git push origin sorting --force-with-lease
```

2023-10-16 20:07 UTC, cypok commented on sort.py
> +    while j >= 0:
А куда логгирование делось? Как-то неправильно конфликт разрешился.

2023-10-17 11:55 UTC, Alexey-shishkin4 commented
merge faster-sorting into sorting branch

2023-10-17 19:49 UTC, cypok requested changes

2023-10-17 19:49 UTC, cypok commented on sort.py
>          print("comparing {} and {}".format(arr[j], arr[min]))
Семантическая ошибка: ниже сравниваются `arr[j]` и `a_i`, а логгируются другие значения.

2023-10-18 06:56 UTC, closed without merging