fix conflict merge sorting and faster-sorting
cypok/tomp-git-exercises pull request #75
Opened 2023-10-16 17:53 UTC by Km1zZzoU

2023-10-16 20:56 UTC, cypok requested changes
К сожалению, не очень понимаю что и зачем вы делали. Нужно было без создания своих коммитов просто слить две ветки. Вы же перед слиянием зачем-то в каждую из них добавили свои коммиты. Так не надо, нужно переделать. Если есть вопросы -- спрашивайте.
Чтобы вернуть в начало:
```
$ git branch -D sorting 
$ git switch --create sorting 32f8878
$ # merge origin/faster-sorting and resolve conflicts here
$ git push origin sorting --force-with-lease
```

2023-10-21 09:00 UTC, Km1zZzoU commented
вроде все таки справился

2023-10-22 07:17 UTC, cypok requested changes

2023-10-22 07:17 UTC, cypok commented on sort.py
>  for i in range(len(arr) - 1):
У вас теперь получился нерабочий код, он не запустится даже.
Надо еще раз повторить процедуру и адекватно разрешить конфликты. Перед тем как делать `git merge --continue` запустите код, он должен работать.

2023-10-22 13:07 UTC, Km1zZzoU commented on sort.py
>  for i in range(len(arr) - 1):
Понял, принял, исправил

2023-10-23 10:02 UTC, closed without merging